#!/usr/bin/env python3
"""Generate firmware and host artefacts from instrumentation.yaml.

Outputs
    Appli/Core/Inc/generated/instr_ids.h
    Tools/instrumentation/generated/instrumentation.json

Both carry the same schema version and schema hash so the host converter can
reject a trace produced by an incompatible firmware build.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

TX_TRACE_USER_EVENT_START = 4096
TX_TRACE_USER_EVENT_END = 65535

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent.parent

DEFAULT_YAML = HERE / "instrumentation.yaml"
DEFAULT_HEADER = PROJECT_ROOT / "Appli" / "Core" / "Inc" / "generated" / "instr_ids.h"
DEFAULT_JSON = HERE / "generated" / "instrumentation.json"


def fnv1a32(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def load_yaml(path: Path) -> dict:
    try:
        import yaml  # type: ignore
    except ImportError:
        sys.exit(
            "PyYAML is required to run the generator: python -m pip install pyyaml\n"
            "(The host converter itself only needs the generated JSON and has no "
            "third-party dependencies.)"
        )
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def normalise(spec: dict) -> dict:
    """Build the canonical, order-stable model used for hashing and output."""
    events = {}
    seen_ids: dict[int, str] = {}
    for name, ev in spec["events"].items():
        eid = int(ev["id"])
        if not TX_TRACE_USER_EVENT_START <= eid <= TX_TRACE_USER_EVENT_END:
            sys.exit(
                f"event {name}: id 0x{eid:X} is outside the TraceX user event range "
                f"[{TX_TRACE_USER_EVENT_START}, {TX_TRACE_USER_EVENT_END}]"
            )
        if eid in seen_ids:
            sys.exit(f"event {name}: id 0x{eid:X} already used by {seen_ids[eid]}")
        seen_ids[eid] = name

        args = list(ev.get("args") or [])
        if len(args) > 4:
            sys.exit(f"event {name}: TraceX records carry at most 4 information fields")
        # Pad so host indexing by position is always well defined.
        while len(args) < 4:
            args.append({"name": f"reserved{len(args)}", "type": "u32"})

        events[name] = {
            "id": eid,
            "track": ev.get("track", "Application"),
            "description": (ev.get("description") or "").strip(),
            "args": [
                {
                    "name": a["name"],
                    "type": a.get("type", "u32"),
                    "unit": a.get("unit"),
                    "enum": a.get("enum"),
                    "description": (a.get("description") or "").strip() or None,
                }
                for a in args
            ],
        }

    model = {
        "schema_version": int(spec["version"]),
        "correlation_key": spec.get("correlation_key", "frame_id"),
        "trace": spec.get("trace", {}),
        "events": events,
        "enums": {k: {str(kk): vv for kk, vv in v.items()} for k, v in (spec.get("enums") or {}).items()},
        "metrics": spec.get("metrics") or {},
        "flows": spec.get("flows") or {},
        "slices": spec.get("slices") or {},
    }
    model["schema_hash"] = _wire_hash(model)
    return model


def _wire_hash(model: dict) -> int:
    """Hash only what the host must agree on to decode a record correctly.

    Descriptions, units, enums, metrics and flows are host-side presentation:
    changing them must not invalidate traces from already-flashed firmware, and
    must not force a reflash. Only the event ids and the name/type/order of the
    four information fields are wire-relevant.
    """
    wire = {
        "schema_version": model["schema_version"],
        "events": {
            name: {
                "id": ev["id"],
                "args": [[a["name"], a["type"]] for a in ev["args"]],
            }
            for name, ev in model["events"].items()
        },
    }
    canonical = json.dumps(wire, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return fnv1a32(canonical)


C_TYPE = {"u32": "uint32_t", "i32": "int32_t"}


def render_header(model: dict) -> str:
    lines = [
        "/* AUTOMATICALLY GENERATED by Tools/instrumentation/gen_instrumentation.py",
        " * Source: Tools/instrumentation/instrumentation.yaml",
        " * Do not edit; edit the YAML and re-run the generator.",
        " */",
        "",
        "#ifndef GENERATED_INSTR_IDS_H",
        "#define GENERATED_INSTR_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define INSTR_SCHEMA_VERSION  {model['schema_version']}U",
        f"#define INSTR_SCHEMA_HASH     0x{model['schema_hash']:08X}U",
        "",
        "typedef enum",
        "{",
    ]
    width = max(len(n) for n in model["events"])
    for name, ev in sorted(model["events"].items(), key=lambda kv: kv[1]["id"]):
        pad = " " * (width - len(name))
        arg_names = ", ".join(a["name"] for a in ev["args"])
        lines.append(f"    INSTR_ID_{name}{pad} = 0x{ev['id']:04X}, /* {arg_names} */")
    lines += [
        "} instr_id_t;",
        "",
        "#endif /* GENERATED_INSTR_IDS_H */",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--yaml", type=Path, default=DEFAULT_YAML)
    ap.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    ap.add_argument("--json", type=Path, default=DEFAULT_JSON)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Fail if the outputs are out of date instead of rewriting them.",
    )
    args = ap.parse_args()

    model = normalise(load_yaml(args.yaml))
    header = render_header(model)
    payload = json.dumps(model, indent=2, sort_keys=True) + "\n"

    outputs = [(args.header, header), (args.json, payload)]

    if args.check:
        stale = [p for p, text in outputs if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print("out of date: " + ", ".join(str(p) for p in stale), file=sys.stderr)
            return 1
        print("instrumentation artefacts are up to date")
        return 0

    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path}")

    print(f"schema version {model['schema_version']}, hash 0x{model['schema_hash']:08X}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
