"""Event id tables for ThreadX 6.4.0 and FileX 6.4.0.

Mirrors Middlewares/ST/threadx/common/inc/tx_trace.h and
Middlewares/ST/filex/common/inc/fx_api.h. Only the fields that are actually
used by the analyzer are named; the rest keep generic labels.
"""

from __future__ import annotations

# Sentinel values written into TX_TRACE_BUFFER_ENTRY.
INVALID_EVENT = 0xFFFFFFFF
THREAD_PTR_ISR = 0xFFFFFFFF
THREAD_PTR_INIT = 0xF0F0F0F0

USER_EVENT_START = 4096
USER_EVENT_END = 65535

# ThreadX object registry types (TX_TRACE_OBJECT_TYPE_*).
OBJECT_TYPES = {
    0: "invalid",
    1: "thread",
    2: "timer",
    3: "queue",
    4: "semaphore",
    5: "mutex",
    6: "event_flags",
    7: "block_pool",
    8: "byte_pool",
}

# event id -> (name, (info1, info2, info3, info4))
THREADX_EVENTS: dict[int, tuple[str, tuple[str, str, str, str]]] = {
    1: ("TX_THREAD_RESUME", ("thread_ptr", "previous_state", "stack_ptr", "next_thread")),
    2: ("TX_THREAD_SUSPEND", ("thread_ptr", "new_state", "stack_ptr", "next_thread")),
    3: ("TX_ISR_ENTER", ("stack_ptr", "isr_number", "system_state", "preempt_disable")),
    4: ("TX_ISR_EXIT", ("stack_ptr", "isr_number", "system_state", "preempt_disable")),
    5: ("TX_TIME_SLICE", ("next_thread", "system_state", "preempt_disable", "stack_ptr")),
    6: ("TX_RUNNING", ("", "", "", "")),
    10: ("TX_BLOCK_ALLOCATE", ("pool_ptr", "memory_ptr", "wait_option", "remaining_blocks")),
    11: ("TX_BLOCK_POOL_CREATE", ("pool_ptr", "pool_start", "total_blocks", "block_size")),
    12: ("TX_BLOCK_POOL_DELETE", ("pool_ptr", "stack_ptr", "", "")),
    13: ("TX_BLOCK_POOL_INFO_GET", ("pool_ptr", "", "", "")),
    14: ("TX_BLOCK_POOL_PERFORMANCE_INFO_GET", ("pool_ptr", "", "", "")),
    15: ("TX_BLOCK_POOL_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    16: ("TX_BLOCK_POOL_PRIORITIZE", ("pool_ptr", "suspended_count", "stack_ptr", "")),
    17: ("TX_BLOCK_RELEASE", ("pool_ptr", "memory_ptr", "suspended", "stack_ptr")),
    20: ("TX_BYTE_ALLOCATE", ("pool_ptr", "memory_ptr", "size_requested", "wait_option")),
    21: ("TX_BYTE_POOL_CREATE", ("pool_ptr", "start_ptr", "pool_size", "stack_ptr")),
    22: ("TX_BYTE_POOL_DELETE", ("pool_ptr", "stack_ptr", "", "")),
    23: ("TX_BYTE_POOL_INFO_GET", ("pool_ptr", "", "", "")),
    24: ("TX_BYTE_POOL_PERFORMANCE_INFO_GET", ("pool_ptr", "", "", "")),
    25: ("TX_BYTE_POOL_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    26: ("TX_BYTE_POOL_PRIORITIZE", ("pool_ptr", "suspended_count", "stack_ptr", "")),
    27: ("TX_BYTE_RELEASE", ("pool_ptr", "memory_ptr", "suspended", "available_bytes")),
    30: ("TX_EVENT_FLAGS_CREATE", ("group_ptr", "stack_ptr", "", "")),
    31: ("TX_EVENT_FLAGS_DELETE", ("group_ptr", "stack_ptr", "", "")),
    32: ("TX_EVENT_FLAGS_GET", ("group_ptr", "requested_flags", "current_flags", "get_option")),
    33: ("TX_EVENT_FLAGS_INFO_GET", ("group_ptr", "", "", "")),
    34: ("TX_EVENT_FLAGS_PERFORMANCE_INFO_GET", ("group_ptr", "", "", "")),
    35: ("TX_EVENT_FLAGS_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    36: ("TX_EVENT_FLAGS_SET", ("group_ptr", "flags_to_set", "set_option", "suspended_count")),
    37: ("TX_EVENT_FLAGS_SET_NOTIFY", ("group_ptr", "", "", "")),
    40: ("TX_INTERRUPT_CONTROL", ("new_posture", "stack_ptr", "", "")),
    50: ("TX_MUTEX_CREATE", ("mutex_ptr", "inheritance", "stack_ptr", "")),
    51: ("TX_MUTEX_DELETE", ("mutex_ptr", "stack_ptr", "", "")),
    52: ("TX_MUTEX_GET", ("mutex_ptr", "wait_option", "owning_thread", "own_count")),
    53: ("TX_MUTEX_INFO_GET", ("mutex_ptr", "", "", "")),
    54: ("TX_MUTEX_PERFORMANCE_INFO_GET", ("mutex_ptr", "", "", "")),
    55: ("TX_MUTEX_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    56: ("TX_MUTEX_PRIORITIZE", ("mutex_ptr", "suspended_count", "stack_ptr", "")),
    57: ("TX_MUTEX_PUT", ("mutex_ptr", "owning_thread", "own_count", "stack_ptr")),
    60: ("TX_QUEUE_CREATE", ("queue_ptr", "message_size", "queue_start", "queue_size")),
    61: ("TX_QUEUE_DELETE", ("queue_ptr", "stack_ptr", "", "")),
    62: ("TX_QUEUE_FLUSH", ("queue_ptr", "stack_ptr", "", "")),
    63: ("TX_QUEUE_FRONT_SEND", ("queue_ptr", "source_ptr", "wait_option", "enqueued")),
    64: ("TX_QUEUE_INFO_GET", ("queue_ptr", "", "", "")),
    65: ("TX_QUEUE_PERFORMANCE_INFO_GET", ("queue_ptr", "", "", "")),
    66: ("TX_QUEUE_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    67: ("TX_QUEUE_PRIORITIZE", ("queue_ptr", "suspended_count", "stack_ptr", "")),
    68: ("TX_QUEUE_RECEIVE", ("queue_ptr", "destination_ptr", "wait_option", "enqueued")),
    69: ("TX_QUEUE_SEND", ("queue_ptr", "source_ptr", "wait_option", "enqueued")),
    70: ("TX_QUEUE_SEND_NOTIFY", ("queue_ptr", "", "", "")),
    80: ("TX_SEMAPHORE_CEILING_PUT", ("semaphore_ptr", "current_count", "suspended_count", "ceiling")),
    81: ("TX_SEMAPHORE_CREATE", ("semaphore_ptr", "initial_count", "stack_ptr", "")),
    82: ("TX_SEMAPHORE_DELETE", ("semaphore_ptr", "stack_ptr", "", "")),
    83: ("TX_SEMAPHORE_GET", ("semaphore_ptr", "wait_option", "current_count", "stack_ptr")),
    84: ("TX_SEMAPHORE_INFO_GET", ("semaphore_ptr", "", "", "")),
    85: ("TX_SEMAPHORE_PERFORMANCE_INFO_GET", ("semaphore_ptr", "", "", "")),
    86: ("TX_SEMAPHORE_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    87: ("TX_SEMAPHORE_PRIORITIZE", ("semaphore_ptr", "suspended_count", "stack_ptr", "")),
    88: ("TX_SEMAPHORE_PUT", ("semaphore_ptr", "current_count", "suspended_count", "stack_ptr")),
    89: ("TX_SEMAPHORE_PUT_NOTIFY", ("semaphore_ptr", "", "", "")),
    100: ("TX_THREAD_CREATE", ("thread_ptr", "priority", "stack_ptr", "stack_size")),
    101: ("TX_THREAD_DELETE", ("thread_ptr", "stack_ptr", "", "")),
    102: ("TX_THREAD_ENTRY_EXIT_NOTIFY", ("thread_ptr", "thread_state", "stack_ptr", "")),
    103: ("TX_THREAD_IDENTIFY", ("", "", "", "")),
    104: ("TX_THREAD_INFO_GET", ("thread_ptr", "thread_state", "", "")),
    105: ("TX_THREAD_PERFORMANCE_INFO_GET", ("thread_ptr", "thread_state", "", "")),
    106: ("TX_THREAD_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
    107: ("TX_THREAD_PREEMPTION_CHANGE", ("thread_ptr", "new_threshold", "old_threshold", "thread_state")),
    108: ("TX_THREAD_PRIORITY_CHANGE", ("thread_ptr", "new_priority", "old_priority", "thread_state")),
    109: ("TX_THREAD_RELINQUISH", ("stack_ptr", "next_thread", "", "")),
    110: ("TX_THREAD_RESET", ("thread_ptr", "thread_state", "", "")),
    111: ("TX_THREAD_RESUME_API", ("thread_ptr", "thread_state", "stack_ptr", "")),
    112: ("TX_THREAD_SLEEP", ("sleep_value", "thread_state", "stack_ptr", "")),
    113: ("TX_THREAD_STACK_ERROR_NOTIFY", ("", "", "", "")),
    114: ("TX_THREAD_SUSPEND_API", ("thread_ptr", "thread_state", "stack_ptr", "")),
    115: ("TX_THREAD_TERMINATE", ("thread_ptr", "thread_state", "stack_ptr", "")),
    116: ("TX_THREAD_TIME_SLICE_CHANGE", ("thread_ptr", "new_timeslice", "old_timeslice", "")),
    117: ("TX_THREAD_WAIT_ABORT", ("thread_ptr", "thread_state", "stack_ptr", "")),
    120: ("TX_TIME_GET", ("current_time", "stack_ptr", "", "")),
    121: ("TX_TIME_SET", ("new_time", "", "", "")),
    122: ("TX_TIMER_ACTIVATE", ("timer_ptr", "", "", "")),
    123: ("TX_TIMER_CHANGE", ("timer_ptr", "initial_ticks", "reschedule_ticks", "")),
    124: ("TX_TIMER_CREATE", ("timer_ptr", "initial_ticks", "reschedule_ticks", "enable")),
    125: ("TX_TIMER_DEACTIVATE", ("timer_ptr", "stack_ptr", "", "")),
    126: ("TX_TIMER_DELETE", ("timer_ptr", "", "", "")),
    127: ("TX_TIMER_INFO_GET", ("timer_ptr", "stack_ptr", "", "")),
    128: ("TX_TIMER_PERFORMANCE_INFO_GET", ("timer_ptr", "", "", "")),
    129: ("TX_TIMER_PERFORMANCE_SYSTEM_INFO_GET", ("", "", "", "")),
}

FILEX_EVENTS: dict[int, tuple[str, tuple[str, str, str, str]]] = {
    201: ("FX_INTERNAL_LOG_SECTOR_CACHE_MISS", ("media_ptr", "sector", "total_misses", "cache_size")),
    202: ("FX_INTERNAL_DIR_CACHE_MISS", ("media_ptr", "total_misses", "", "")),
    203: ("FX_INTERNAL_MEDIA_FLUSH", ("media_ptr", "dirty_sectors", "", "")),
    204: ("FX_INTERNAL_DIR_ENTRY_READ", ("media_ptr", "", "", "")),
    205: ("FX_INTERNAL_DIR_ENTRY_WRITE", ("media_ptr", "", "", "")),
    206: ("FX_INTERNAL_IO_DRIVER_READ", ("media_ptr", "sector", "sector_count", "buffer")),
    207: ("FX_INTERNAL_IO_DRIVER_WRITE", ("media_ptr", "sector", "sector_count", "buffer")),
    208: ("FX_INTERNAL_IO_DRIVER_FLUSH", ("media_ptr", "", "", "")),
    209: ("FX_INTERNAL_IO_DRIVER_ABORT", ("media_ptr", "", "", "")),
    210: ("FX_INTERNAL_IO_DRIVER_INIT", ("media_ptr", "", "", "")),
    211: ("FX_INTERNAL_IO_DRIVER_BOOT_READ", ("media_ptr", "buffer", "", "")),
    212: ("FX_INTERNAL_IO_DRIVER_RELEASE_SECTORS", ("media_ptr", "sector", "sector_count", "")),
    213: ("FX_INTERNAL_IO_DRIVER_BOOT_WRITE", ("media_ptr", "buffer", "", "")),
    214: ("FX_INTERNAL_IO_DRIVER_UNINIT", ("media_ptr", "", "", "")),
    220: ("FX_DIRECTORY_ATTRIBUTES_READ", ("media_ptr", "directory_name", "attributes", "")),
    221: ("FX_DIRECTORY_ATTRIBUTES_SET", ("media_ptr", "directory_name", "attributes", "")),
    222: ("FX_DIRECTORY_CREATE", ("media_ptr", "directory_name", "", "")),
    223: ("FX_DIRECTORY_DEFAULT_GET", ("media_ptr", "return_path_name", "", "")),
    224: ("FX_DIRECTORY_DEFAULT_SET", ("media_ptr", "new_path_name", "", "")),
    225: ("FX_DIRECTORY_DELETE", ("media_ptr", "directory_name", "", "")),
    226: ("FX_DIRECTORY_FIRST_ENTRY_FIND", ("media_ptr", "directory_name", "", "")),
    227: ("FX_DIRECTORY_FIRST_FULL_ENTRY_FIND", ("media_ptr", "directory_name", "", "")),
    228: ("FX_DIRECTORY_INFORMATION_GET", ("media_ptr", "directory_name", "", "")),
    229: ("FX_DIRECTORY_LOCAL_PATH_CLEAR", ("media_ptr", "", "", "")),
    230: ("FX_DIRECTORY_LOCAL_PATH_GET", ("media_ptr", "return_path_name", "", "")),
    231: ("FX_DIRECTORY_LOCAL_PATH_RESTORE", ("media_ptr", "local_path_ptr", "", "")),
    232: ("FX_DIRECTORY_LOCAL_PATH_SET", ("media_ptr", "local_path_ptr", "new_path_name", "")),
    233: ("FX_DIRECTORY_LONG_NAME_GET", ("media_ptr", "short_file_name", "long_file_name", "")),
    234: ("FX_DIRECTORY_NAME_TEST", ("media_ptr", "directory_name", "", "")),
    235: ("FX_DIRECTORY_NEXT_ENTRY_FIND", ("media_ptr", "directory_name", "", "")),
    236: ("FX_DIRECTORY_NEXT_FULL_ENTRY_FIND", ("media_ptr", "directory_name", "", "")),
    237: ("FX_DIRECTORY_RENAME", ("media_ptr", "old_directory_name", "new_directory_name", "")),
    238: ("FX_DIRECTORY_SHORT_NAME_GET", ("media_ptr", "long_file_name", "short_file_name", "")),
    239: ("FX_FILE_ALLOCATE", ("file_ptr", "size", "previous_size", "new_size")),
    240: ("FX_FILE_ATTRIBUTES_READ", ("media_ptr", "file_name", "attributes", "")),
    241: ("FX_FILE_ATTRIBUTES_SET", ("media_ptr", "file_name", "attributes", "")),
    242: ("FX_FILE_BEST_EFFORT_ALLOCATE", ("file_ptr", "size", "actual_size_allocated", "")),
    243: ("FX_FILE_CLOSE", ("file_ptr", "", "file_size", "")),
    244: ("FX_FILE_CREATE", ("media_ptr", "file_name", "", "")),
    245: ("FX_FILE_DATE_TIME_SET", ("media_ptr", "file_name", "year", "month")),
    246: ("FX_FILE_DELETE", ("media_ptr", "file_name", "", "")),
    247: ("FX_FILE_OPEN", ("media_ptr", "file_ptr", "file_name", "open_type")),
    248: ("FX_FILE_READ", ("file_ptr", "buffer_ptr", "request_size", "actual_size")),
    249: ("FX_FILE_RELATIVE_SEEK", ("file_ptr", "byte_offset", "seek_from", "previous_offset")),
    250: ("FX_FILE_RENAME", ("media_ptr", "old_file_name", "new_file_name", "")),
    251: ("FX_FILE_SEEK", ("file_ptr", "byte_offset", "previous_offset", "")),
    252: ("FX_FILE_TRUNCATE", ("file_ptr", "size", "previous_size", "new_size")),
    253: ("FX_FILE_TRUNCATE_RELEASE", ("file_ptr", "size", "previous_size", "new_size")),
    254: ("FX_FILE_WRITE", ("file_ptr", "buffer_ptr", "size", "bytes_written")),
    255: ("FX_MEDIA_ABORT", ("media_ptr", "", "", "")),
    256: ("FX_MEDIA_CACHE_INVALIDATE", ("media_ptr", "", "", "")),
    257: ("FX_MEDIA_CHECK", ("media_ptr", "scratch_memory", "scratch_size", "errors")),
    258: ("FX_MEDIA_CLOSE", ("media_ptr", "", "", "")),
    259: ("FX_MEDIA_FLUSH", ("media_ptr", "", "", "")),
    260: ("FX_MEDIA_FORMAT", ("media_ptr", "root_entries", "sectors", "sectors_per_cluster")),
    261: ("FX_MEDIA_OPEN", ("media_ptr", "media_driver", "memory_ptr", "memory_size")),
    262: ("FX_MEDIA_READ", ("media_ptr", "logical_sector", "buffer_ptr", "bytes_read")),
    263: ("FX_MEDIA_SPACE_AVAILABLE", ("media_ptr", "available_bytes_ptr", "available_clusters", "")),
    264: ("FX_MEDIA_VOLUME_GET", ("media_ptr", "volume_name", "volume_source", "")),
    265: ("FX_MEDIA_VOLUME_SET", ("media_ptr", "volume_name", "", "")),
}


def lookup(event_id: int) -> tuple[str, tuple[str, str, str, str]] | None:
    """Return (name, info-field labels) for a native ThreadX/FileX event."""
    if event_id in THREADX_EVENTS:
        return THREADX_EVENTS[event_id]
    if event_id in FILEX_EVENTS:
        return FILEX_EVENTS[event_id]
    return None
